backend:
  name: github
  repo: synectiks-code/cms-synectiks-website
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img
media_library:
  name: cloudinary
  config:
    cloud_name: papu
    api_key: gCnVUy2-lWSZ_-PyxywjiFgMDck
    default_transformations:
      - - fetch_format: auto
          width: 160
          quality: auto
          crop: scale

collections:
  - name: "scenario"
    label: "Scenario"
    folder: "src/pages/scenario"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "scenario-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: Actors List,
          name: scenarios,
          widget: list,
          fields:
            [
              { label: Image, name: img, widget: text },
              { label: Name, name: name, widget: text },
              {
                label: Use Cases,
                name: subItems,
                widget: list,
                fields:
                  [
                    { label: Image, name: img, widget: text },
                    { label: Name, name: name, widget: text },  
                    {
                      label: Use Case Slider,
                      name: useCaseSlider,
                      widget: list,
                      fields:
                        [
                          { label: Image, name: img, widget: text },
                          { label: Name, name: name, widget: text },
                          { label: Text, name: text, widget: text },                   
                        ]
                    }                 
                  ]
              }
            ]
        }
      - {
          label: Slider,
          name: slider,
          widget: list,
          fields:
            [
              { label: Image, name: img, widget: text },
              { label: Name, name: name, widget: text },
              { label: Text, name: text, widget: text },
              {
                label: More Details,
                name: moreDetails,
                widget: object,
                fields:
                  [
                    { label: More Details Name, name: moreDetailsName, widget: text },
                    { label: More Details Text, name: moreDetailsText, widget: text },
                    { 
                      label: More Details Image, 
                      name: moreDetailsImage, 
                      widget: list,
                      fields:
                        [
                          { label: Image, name: img, widget: text },
                        ], 
                    },                    
                  ],
              }
            ],
        }
  - name: "service"
    label: "Service"
    folder: "src/pages/service"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "service-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: Page,
          name: page,
          widget: list,
          fields:
            [
              { label: Heading, name: heading, widget: string },
              { label: Description, name: description, widget: text },
            ],
        }
      - { label: "Category", name: "category", widget: "list" }  
  - name: "workflowpost"
    label: "Workflow Post"
    folder: "src/pages/workflowpost"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "workflow-page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Workflow JSON", name: "workflowjson", widget: "object", fields: [{label: Data, name: data, widget: text}]}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - { label: Title, name: title, widget: string }
      - file: "src/pages/survey/index.md"
        label: "Survey"
        name: "survey"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "survey-page"}
          - {label: "Survey JSON", name: "surveyjson", widget: "object", fields: [{label: Data, name: data, widget: text}]}